version: '3.4'
services:
  web:
    image: webtree/org.web-tree.mystuff.web
    ports:
      - "31001:80"
    deploy:
      replicas: 3
    networks:
      - back
  back:
    image: webtree/org.web-tree.mystuff.back
    deploy:
      replicas: 3
    ports:
      - "31002:9000"
    environment:
      - spring.data.neo4j.uri=http://neo4j:7474
    links:
      - neo4j:neo4j
    networks:
          - back
  neo4j:
    deploy:
      replicas: 3
    image: neo4j:3.0
    environment:
      - NEO4J_AUTH=none
    ports:
     - "7474:7474"
    volumes:
      - neo4j-data:/data
    networks:
      - back
volumes:
  neo4j-data:
networks:
  back:
    driver: overlay